version: "3"
services:
  frontend-react:
    build: ./frontend-react
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"

  backend-node:
    build: ./backend-node
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports: 
      - "8080:8080"
    restart: on-failure